export enum MoyenPaiement {
    ESPECE= 'ESPECE',
    CHEQUE= 'CHEQUE',
    VERSEMENT= 'VERSEMENT',
    VIREMENT= 'VIREMENT',
    CARTE_BANCAIRE= 'CARTE_BANCAIRE',
    EFFETS= 'EFFETS',
    PRELEVEMENT_BANCAIRE= 'PRELEVEMENT_BANCAIRE',
}
