export enum AccountMovementStatus {
    AWAITING_TREATMENT= 'AWAITING_TREATMENT',
    COMPTABILISER= 'COMPTABILISER', // COMPTABILISER
    DEPOSIT= 'DEPOSIT', // VERSER
    EXECUTE= 'EXECUTE', //
    CANCELED= 'CANCELED'
}
