export class SoustraitantsFakeData {
    public static sousTraitants = [
        {
            id: 1,
            firstName: 'LAHCEN ABOUSALIH',
            company: 'Yotz PVT LTD',
            role: 'Editor',
            username: 'gslixby0',
            villeIntitule: 'El Salvador',
            phoneNumber: '(479) 232-9151',
            email: 'gslixby0@abc.net.au',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '',
            soldeValue: 100000,
            soldeStatus: 'CREDITEUR',

        },
        {
            id: 2,
            firstName: 'Halsey Redmore',
            company: 'Skinder PVT LTD',
            role: 'Author',
            username: 'hredmore1',
            villeIntitule: 'Albania',
            phoneNumber: '(472) 607-9137',
            email: 'hredmore1@imgur.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '',
            soldeValue: 20000,
            soldeStatus: 'CREDITEUR',
        },
        {
            id: 3,
            firstName: 'Marjory Sicely',
            company: 'Oozz PVT LTD',
            role: 'Maintainer',
            username: 'msicely2',
            villeIntitule: 'Russia',
            phoneNumber: '(321) 264-4599',
            email: 'msicely2@who.int',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '',
            soldeValue: 30000,
            soldeStatus: 'CREDITEUR',
        },
        {
            id: 4,
            firstName: 'Cyrill Risby',
            company: 'Oozz PVT LTD',
            role: 'Maintainer',
            username: 'crisby3',
            villeIntitule: 'China',
            phoneNumber: '(923) 690-6806',
            email: 'crisby3@wordpress.com',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 5,
            firstName: 'Maggy Hurran',
            company: 'Aimbo PVT LTD',
            role: 'Subscriber',
            username: 'mhurran4',
            villeIntitule: 'Pakistan',
            phoneNumber: '(669) 914-1078',
            email: 'mhurran4@yahoo.co.jp',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 6,
            firstName: 'Silvain Halstead',
            company: 'Jaxbean PVT LTD',
            role: 'Author',
            username: 'shalstead5',
            villeIntitule: 'China',
            phoneNumber: '(958) 973-3093',
            email: 'shalstead5@shinystat.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 7,
            firstName: 'Breena Gallemore',
            company: 'Jazzy PVT LTD',
            role: 'Subscriber',
            username: 'bgallemore6',
            villeIntitule: 'Canada',
            phoneNumber: '(825) 977-8152',
            email: 'bgallemore6@boston.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 8,
            firstName: 'Kathryne Liger',
            company: 'Pixoboo PVT LTD',
            role: 'Author',
            username: 'kliger7',
            villeIntitule: 'France',
            phoneNumber: '(187) 440-0934',
            email: 'kliger7@vinaora.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 9,
            firstName: 'Franz Scotfurth',
            company: 'Tekfly PVT LTD',
            role: 'Subscriber',
            username: 'fscotfurth8',
            villeIntitule: 'China',
            phoneNumber: '(978) 146-5443',
            email: 'fscotfurth8@dailymotion.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 10,
            firstName: 'Jillene Bellany',
            company: 'Gigashots PVT LTD',
            role: 'Maintainer',
            username: 'jbellany9',
            villeIntitule: 'Jamaica',
            phoneNumber: '(589) 284-6732',
            email: 'jbellany9@kickstarter.com',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 11,
            firstName: 'Jonah Wharlton',
            company: 'Eare PVT LTD',
            role: 'Subscriber',
            username: 'jwharltona',
            villeIntitule: 'United States',
            phoneNumber: '(176) 532-6824',
            email: 'jwharltona@oakley.com',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 12,
            firstName: 'Seth Hallam',
            company: 'Yakitri PVT LTD',
            role: 'Subscriber',
            username: 'shallamb',
            villeIntitule: 'Peru',
            phoneNumber: '(234) 464-0600',
            email: 'shallamb@hugedomains.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 13,
            firstName: 'Yoko Pottie',
            company: 'Leenti PVT LTD',
            role: 'Subscriber',
            username: 'ypottiec',
            villeIntitule: 'Philippines',
            phoneNumber: '(907) 284-5083',
            email: 'ypottiec@privacy.gov.au',
            currentPlan: 'Personne Physique',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 14,
            firstName: 'Maximilianus Krause',
            company: 'Digitube PVT LTD',
            role: 'Author',
            username: 'mkraused',
            villeIntitule: 'Democratic Republic of the Congo',
            phoneNumber: '(167) 135-7392',
            email: 'mkraused@stanford.edu',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 15,
            firstName: 'Zsazsa McCleverty',
            company: 'Kaymbo PVT LTD',
            role: 'Maintainer',
            username: 'zmcclevertye',
            villeIntitule: 'France',
            phoneNumber: '(317) 409-6565',
            email: 'zmcclevertye@soundcloud.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 16,
            firstName: 'Bentlee Emblin',
            company: 'Yambee PVT LTD',
            role: 'Author',
            username: 'bemblinf',
            villeIntitule: 'Spain',
            phoneNumber: '(590) 606-1056',
            email: 'bemblinf@wired.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 17,
            firstName: 'Brockie Myles',
            company: 'Wikivu PVT LTD',
            role: 'Maintainer',
            username: 'bmylesg',
            villeIntitule: 'Poland',
            phoneNumber: '(553) 225-9905',
            email: 'bmylesg@amazon.com',
            currentPlan: 'Personne Physique',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 18,
            firstName: 'Bertha Biner',
            company: 'Twinte PVT LTD',
            role: 'Editor',
            username: 'bbinerh',
            villeIntitule: 'Yemen',
            phoneNumber: '(901) 916-9287',
            email: 'bbinerh@mozilla.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 19,
            firstName: 'Travus Bruntjen',
            company: 'Cogidoo PVT LTD',
            role: 'Admin',
            username: 'tbruntjeni',
            villeIntitule: 'France',
            phoneNumber: '(524) 586-6057',
            email: 'tbruntjeni@sitemeter.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 20,
            firstName: 'Wesley Burland',
            company: 'Bubblemix PVT LTD',
            role: 'Editor',
            username: 'wburlandj',
            villeIntitule: 'Honduras',
            phoneNumber: '(569) 683-1292',
            email: 'wburlandj@uiuc.edu',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 21,
            firstName: 'Stu Delamaine',
            company: 'Oyoloo PVT LTD',
            role: 'Author',
            username: 'sdelamainek',
            villeIntitule: 'South Africa',
            phoneNumber: '(829) 537-0057',
            email: 'sdelamainek@who.int',
            currentPlan: 'Personne Physique',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 22,
            firstName: 'Jameson Lyster',
            company: 'Quaxo PVT LTD',
            role: 'Editor',
            username: 'jlysterl',
            villeIntitule: 'Ukraine',
            phoneNumber: '(593) 624-0222',
            email: 'jlysterl@guardian.co.uk',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 100000, soldeStatus: 'EN REGLE',
        },
        {
            id: 23,
            firstName: 'Kare Skitterel',
            company: 'Ainyx PVT LTD',
            role: 'Maintainer',
            username: 'kskitterelm',
            villeIntitule: 'Poland',
            phoneNumber: '(254) 845-4107',
            email: 'kskitterelm@washingtonpost.com',
            currentPlan: 'Personne Physique',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 24,
            firstName: 'Cleavland Hatherleigh',
            company: 'Flipopia PVT LTD',
            role: 'Admin',
            username: 'chatherleighn',
            villeIntitule: 'Brazil',
            phoneNumber: '(700) 783-7498',
            email: 'chatherleighn@washington.edu',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 25,
            firstName: 'Adeline Micco',
            company: 'Topicware PVT LTD',
            role: 'Admin',
            username: 'amiccoo',
            villeIntitule: 'France',
            phoneNumber: '(227) 598-1841',
            email: 'amiccoo@whitehouse.gov',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 26,
            firstName: 'Hugh Hasson',
            company: 'Skinix PVT LTD',
            role: 'Admin',
            username: 'hhassonp',
            villeIntitule: 'China',
            phoneNumber: '(582) 516-1324',
            email: 'hhassonp@bizjournals.com',
            currentPlan: 'Personne Physique',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 27,
            firstName: 'Germain Jacombs',
            company: 'Youopia PVT LTD',
            role: 'Editor',
            username: 'gjacombsq',
            villeIntitule: 'Zambia',
            phoneNumber: '(137) 467-5393',
            email: 'gjacombsq@jigsy.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 28,
            firstName: 'Bree Kilday',
            company: 'Jetpulse PVT LTD',
            role: 'Maintainer',
            username: 'bkildayr',
            villeIntitule: 'Portugal',
            phoneNumber: '(412) 476-0854',
            email: 'bkildayr@mashable.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 29,
            firstName: 'Candice Pinyon',
            company: 'Kare PVT LTD',
            role: 'Maintainer',
            username: 'cpinyons',
            villeIntitule: 'Sweden',
            phoneNumber: '(170) 683-1520',
            email: 'cpinyons@behance.net',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 30,
            firstName: 'Isabel Mallindine',
            company: 'Voomm PVT LTD',
            role: 'Subscriber',
            username: 'imallindinet',
            villeIntitule: 'Slovenia',
            phoneNumber: '(332) 803-1983',
            email: 'imallindinet@shinystat.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 31,
            firstName: 'Gwendolyn Meineken',
            company: 'Oyondu PVT LTD',
            role: 'Admin',
            username: 'gmeinekenu',
            villeIntitule: 'Moldova',
            phoneNumber: '(551) 379-7460',
            email: 'gmeinekenu@hc360.com',
            currentPlan: 'Personne Physique',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 32,
            firstName: 'Rafaellle Snowball',
            company: 'Fivespan PVT LTD',
            role: 'Editor',
            username: 'rsnowballv',
            villeIntitule: 'Philippines',
            phoneNumber: '(974) 829-0911',
            email: 'rsnowballv@indiegogo.com',
            currentPlan: 'Personne Physique',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 33,
            firstName: 'Rochette Emer',
            company: 'Thoughtworks PVT LTD',
            role: 'Admin',
            username: 'remerw',
            villeIntitule: 'North Korea',
            phoneNumber: '(841) 889-3339',
            email: 'remerw@blogtalkradio.com',
            currentPlan: 'Personne Physique',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 34,
            firstName: 'Ophelie Fibbens',
            company: 'Jaxbean PVT LTD',
            role: 'Subscriber',
            username: 'ofibbensx',
            villeIntitule: 'Indonesia',
            phoneNumber: '(764) 885-7351',
            email: 'ofibbensx@booking.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 35,
            firstName: 'Stephen MacGilfoyle',
            company: 'Browseblab PVT LTD',
            role: 'Maintainer',
            username: 'smacgilfoyley',
            villeIntitule: 'Japan',
            phoneNumber: '(350) 589-8520',
            email: 'smacgilfoyley@bigcartel.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 36,
            firstName: 'Bradan Rosebotham',
            company: 'Agivu PVT LTD',
            role: 'Subscriber',
            username: 'brosebothamz',
            villeIntitule: 'Belarus',
            phoneNumber: '(882) 933-2180',
            email: 'brosebothamz@tripadvisor.com',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 37,
            firstName: 'Skip Hebblethwaite',
            company: 'Katz PVT LTD',
            role: 'Admin',
            username: 'shebblethwaite10',
            villeIntitule: 'Canada',
            phoneNumber: '(610) 343-1024',
            email: 'shebblethwaite10@arizona.edu',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 38,
            firstName: 'Moritz Piccard',
            company: 'Twitternation PVT LTD',
            role: 'Maintainer',
            username: 'mpiccard11',
            villeIntitule: 'Croatia',
            phoneNumber: '(365) 277-2986',
            email: 'mpiccard11@vimeo.com',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 39,
            firstName: 'Tyne Widmore',
            company: 'Yombu PVT LTD',
            role: 'Subscriber',
            username: 'twidmore12',
            villeIntitule: 'Finland',
            phoneNumber: '(531) 731-0928',
            email: 'twidmore12@bravesites.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 40,
            firstName: 'Florenza Desporte',
            company: 'Kamba PVT LTD',
            role: 'Author',
            username: 'fdesporte13',
            villeIntitule: 'Ukraine',
            phoneNumber: '(312) 104-2638',
            email: 'fdesporte13@omniture.com',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 41,
            firstName: 'Edwina Baldetti',
            company: 'Dazzlesphere PVT LTD',
            role: 'Maintainer',
            username: 'ebaldetti14',
            villeIntitule: 'Haiti',
            phoneNumber: '(315) 329-3578',
            email: 'ebaldetti14@theguardian.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 42,
            firstName: 'Benedetto Rossiter',
            company: 'Mybuzz PVT LTD',
            role: 'Editor',
            username: 'brossiter15',
            villeIntitule: 'Indonesia',
            phoneNumber: '(323) 175-6741',
            email: 'brossiter15@craigslist.org',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 43,
            firstName: 'Micaela McNirlan',
            company: 'Tambee PVT LTD',
            role: 'Admin',
            username: 'mmcnirlan16',
            villeIntitule: 'Indonesia',
            phoneNumber: '(242) 952-0916',
            email: 'mmcnirlan16@hc360.com',
            currentPlan: 'Personne Physique',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 44,
            firstName: 'Vladamir Koschek',
            company: 'Centimia PVT LTD',
            role: 'Author',
            username: 'vkoschek17',
            villeIntitule: 'Guatemala',
            phoneNumber: '(531) 758-8335',
            email: 'vkoschek17@abc.net.au',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 45,
            firstName: 'Corrie Perot',
            company: 'Flipopia PVT LTD',
            role: 'Subscriber',
            username: 'cperot18',
            villeIntitule: 'China',
            phoneNumber: '(659) 385-6808',
            email: 'cperot18@goo.ne.jp',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 46,
            firstName: 'Saunder Offner',
            company: 'Skalith PVT LTD',
            role: 'Maintainer',
            username: 'soffner19',
            villeIntitule: 'Poland',
            phoneNumber: '(200) 586-2264',
            email: 'soffner19@mac.com',
            currentPlan: 'Enterprise',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 47,
            firstName: 'Karena Courtliff',
            company: 'Feedfire PVT LTD',
            role: 'Admin',
            username: 'kcourtliff1a',
            villeIntitule: 'China',
            phoneNumber: '(478) 199-0020',
            email: 'kcourtliff1a@bbc.co.uk',
            currentPlan: 'Personne Physique',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 48,
            firstName: 'Onfre Wind',
            company: 'Thoughtmix PVT LTD',
            role: 'Admin',
            username: 'owind1b',
            villeIntitule: 'Ukraine',
            phoneNumber: '(344) 262-7270',
            email: 'owind1b@yandex.ru',
            currentPlan: 'Personne Physique',
            status: 'suspendu',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 49,
            firstName: 'Paulie Durber',
            company: 'Babbleblab PVT LTD',
            role: 'Subscriber',
            username: 'pdurber1c',
            villeIntitule: 'Sweden',
            phoneNumber: '(694) 676-1275',
            email: 'pdurber1c@gov.uk',
            currentPlan: 'Enterprise',
            status: 'inactif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        },
        {
            id: 50,
            firstName: 'Beverlie Krabbe',
            company: 'Kaymbo PVT LTD',
            role: 'Editor',
            username: 'bkrabbe1d',
            villeIntitule: 'China',
            phoneNumber: '(397) 294-5153',
            email: 'bkrabbe1d@home.pl',
            currentPlan: 'Enterprise',
            status: 'actif',
            avatar: '', soldeValue: 0, soldeStatus: 'EN REGLE',
        }
    ];
   /*
    public static sousTraitants = [
        [
            {
                id: '619e4d4e7df6540e05bcb323',
                civilite: null,
                prenom: null,
                fullName: 'ABDELAZIZ AIT BEN ESSAID',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null,
                status: 'actif',
                avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb327',
                civilite: null,
                prenom: null,
                fullName: 'ABRAJ BATIMENT',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null,
                status: 'actif',
                avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb325',
                civilite: null,
                prenom: null,
                fullName: 'ABDELKBIR KHALLOUK',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb328',
                civilite: null,
                prenom: null,
                fullName: 'ACHAMAL DU NORD',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb324',
                civilite: null,
                prenom: null,
                fullName: 'ABDELFETAH EL AZZANY',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb326',
                civilite: null,
                prenom: null,
                fullName: 'ABDERRAHIM EDDEHBI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb32a',
                civilite: null,
                prenom: null,
                fullName: 'AMAZIL',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb32f',
                civilite: null,
                prenom: null,
                fullName: 'BONYAN AL ARAB',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb329',
                civilite: null,
                prenom: null,
                fullName: 'AHMED ELHAMDI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb32c',
                civilite: null,
                prenom: null,
                fullName: 'ATLAS CONS ',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb32d',
                civilite: null,
                prenom: null,
                fullName: 'BAB SAHARA SNC',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb330',
                civilite: null,
                prenom: null,
                fullName: 'CHEGATIK DE TRAVAUX',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb331',
                civilite: null,
                prenom: null,
                fullName: 'CHELLAB BÂTIMENT',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb32e',
                civilite: null,
                prenom: null,
                fullName: 'BENORHO',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb32b',
                civilite: null,
                prenom: null,
                fullName: 'AMZD BATIMENT',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb332',
                civilite: null,
                prenom: null,
                fullName: 'DRAGON DESIGN',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb333',
                civilite: null,
                prenom: null,
                fullName: 'DRISS OURGAL',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb334',
                civilite: null,
                prenom: null,
                fullName: 'ECOGEN',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb335',
                civilite: null,
                prenom: null,
                fullName: 'EL GHOUCH OMAR',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb336',
                civilite: null,
                prenom: null,
                fullName: 'ERRAMI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb337',
                civilite: null,
                prenom: null,
                fullName: 'FAMIMID ISMAILI TRAV',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb338',
                civilite: null,
                prenom: null,
                fullName: 'HAMID IMAGHRI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb339',
                civilite: null,
                prenom: null,
                fullName: 'HARRY',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb33a',
                civilite: null,
                prenom: null,
                fullName: 'HIGH WORKS',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb33b',
                civilite: null,
                prenom: null,
                fullName: 'INDUSTRIE EQUIPEMENTS',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb33c',
                civilite: null,
                prenom: null,
                fullName: 'INFRALEC',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb33d',
                civilite: null,
                prenom: null,
                fullName: 'JOUHARI CLIMATISATION',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb33e',
                civilite: null,
                prenom: null,
                fullName: 'KADIFARS',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb33f',
                civilite: null,
                prenom: null,
                fullName: 'KARIM FANI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb340',
                civilite: null,
                prenom: null,
                fullName: 'KETRAFIC SARL',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb341',
                civilite: null,
                prenom: null,
                fullName: 'MC MAROC (IMOULA)',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb342',
                civilite: null,
                prenom: null,
                fullName: 'MEGASONTE',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb343',
                civilite: null,
                prenom: null,
                fullName: 'MOGADOR MARBRE',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb344',
                civilite: null,
                prenom: null,
                fullName: 'MOHAMMED ASSADKI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb345',
                civilite: null,
                prenom: null,
                fullName: 'MUR BAND',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb346',
                civilite: null,
                prenom: null,
                fullName: 'MUSTAPHA BOURBAB',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb347',
                civilite: null,
                prenom: null,
                fullName: 'NAGUA TRAD',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb348',
                civilite: null,
                prenom: null,
                fullName: 'NAMIR',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb349',
                civilite: null,
                prenom: null,
                fullName: 'PIC ENERGIE ',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb34a',
                civilite: null,
                prenom: null,
                fullName: 'POLY DAL',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb34b',
                civilite: null,
                prenom: null,
                fullName: 'RACHID AMAZOUZ',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb34c',
                civilite: null,
                prenom: null,
                fullName: 'ROPEC',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb34d',
                civilite: null,
                prenom: null,
                fullName: 'S.M.T JARDIN',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb34e',
                civilite: null,
                prenom: null,
                fullName: 'SGM EQUIPEMENT',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb34f',
                civilite: null,
                prenom: null,
                fullName: 'SILABA',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb350',
                civilite: null,
                prenom: null,
                fullName: 'STRADY DE CONST',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb351',
                civilite: null,
                prenom: null,
                fullName: 'TAAMIR DEMNATE',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb352',
                civilite: null,
                prenom: null,
                fullName: 'TAZANOVA',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb353',
                civilite: null,
                prenom: null,
                fullName: 'TIWIZI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb354',
                civilite: null,
                prenom: null,
                fullName: 'TOUFAYOUS',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb35a',
                civilite: null,
                prenom: null,
                fullName: 'VARGA TUILE',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb356',
                civilite: null,
                prenom: null,
                fullName: 'TRADITIONART',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb35c',
                civilite: null,
                prenom: null,
                fullName: 'YOUSSEF RAFIK',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb359',
                civilite: null,
                prenom: null,
                fullName: 'VALMONDIAL',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb35d',
                civilite: null,
                prenom: null,
                fullName: 'ZRIROU RACHID',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb358',
                civilite: null,
                prenom: null,
                fullName: 'UNLIMITED EVENTS',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb35b',
                civilite: null,
                prenom: null,
                fullName: 'WALGANE DE TRAVAUX',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb357',
                civilite: null,
                prenom: null,
                fullName: 'TRAVTAZI',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            },
            {
                id: '619e4d4e7df6540e05bcb355',
                civilite: null,
                prenom: null,
                fullName: 'TOZAW TRAVAUX',
                adresse: null,
                tel: null,
                gsm: null,
                fax: null,
                email: null,
                siteWeb: null,
                ice: null,
                cin: null,
                indiceFiscal: null,
                patente: null,
                rc: null,
                cnss: null,
                rib: null,
                dateCreation: null,
                soldeValue: 0.0,
                formeJuridique: null,
                activite: null, status: 'actif',avatar: '',soldeValue:0, soldeStatus:'EN REGLE',            ,
                ville: null,
                pays: null,
                banque: null
            }
        ]
    ];
    */
}
